### PR TITLE
Fix invalidpointer

### PR DESCRIPTION
**Pull request by johnmauff**
This PR addresses an invalid pointer error that occurs with the CostFunctionXYZ::SItransform() method is called from the CostFunctionXYZ::outputAnalysis() method.  This bug fix was identified by @sjsprecious

### CODE REVIEW

**Review by sjsprecious — APPROVED** [review]
LGTM!

**Review by mmbell — APPROVED** [review]
This seems fine to me.

**Comment by johnmauff** [comment]
@tingyucha Could you take a look at this PR?

**Comment by johnmauff** [comment]
Changes were made to the main versus master branch

**Pull request closed without merging**
